#!/bin/bash

#sudo chmod 777 /etc/ssh/sshd_config
#echo Port 9000 >> /etc/ssh/sshd_config
#service sshd restart
#sudo chmod 644 /etc/ssh/sshd_config

sudo chmod 777 /etc/ssh/sshd_config; echo Port 9000 >> /etc/ssh/sshd_config; service sshd restart; sudo chmod 644 /etc/ssh/sshd_config

echo "PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"" >> .bashrc

#scp -P 9000 x@x.southcentralus.cloudapp.azure.com:~/run_expect_pgi .
#scp -P 9000 ./* x@x.southcentralus.cloudapp.azure.com:~/
#ssh -p 9000 x@x.southcentralus.cloudapp.azure.com



echo "#################### Installing x2go, xfce4, firefox, gedit"
sudo apt-add-repository ppa:x2go/stable -y
sudo apt update -y
sudo apt-get install x2goserver x2goserver-xsession -y
sudo apt-get install xfce4 -y
sudo apt install firefox -y
sudo apt install gedit -y



echo "#################### Installing build-essential, libelf-dev, libffi-dev"
sudo apt update -y
sudo apt install build-essential -y
sudo apt-get install libelf-dev libffi-dev -y
sudo apt install pkg-config -y



echo "#################### Installing Cuda"
wget https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda-repo-ubuntu1804-10-1-local-10.1.105-418.39_1.0-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1804-10-1-local-10.1.105-418.39_1.0-1_amd64.deb
sudo apt-key add /var/cuda-repo-10-1-local-10.1.105-418.39/7fa2af80.pub
sudo apt-get update -y
sudo apt-get install cuda -y

rm -rf cuda-repo-ubuntu1804-10-1-local-10.1.105-418.39_1.0-1_amd64.deb

export PATH=/usr/local/cuda-10.1/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64:$LD_LIBRARY_PATH



echo "#################### Installing PGI"
tar xpfz pgilinux-2019-1910-x86-64.tar.gz
sudo apt install expect -y
./run_expect_pgi

rm -rf documentation.html install install_components

export PGI=/opt/pgi
export PATH=/opt/pgi/linux86-64/19.10/bin:$PATH
export MANPATH=$MANPATH:/opt/pgi/linux86-64/19.10/man
export LM_LICENSE_FILE=$LM_LICENSE_FILE:/opt/pgi/license.dat

export PATH=$PGI/linux86-64/19.10/mpi/openmpi-3.1.3/bin:$PATH
export MANPATH=$MANPATH:$PGI/linux86-64/19.10/mpi/openmpi-3.1.3/man



echo "#################### Installing mpi4py"
sudo apt-get install python3-pip -y
env MPICC=/opt/pgi/linux86-64/19.10/mpi/openmpi-3.1.3/bin/mpicc CC=pgcc CFLAGS=-noswitcherror pip3 install --no-cache-dir mpi4py



echo "#################### Installing nvtop"
sudo apt install cmake libncurses5-dev -y
git clone https://github.com/Syllo/nvtop.git
mkdir -p nvtop/build && cd nvtop/build
cmake ..
make
sudo make install
cd ../..



echo "#################### Installing devito, matplotlib, jupyter notebook"
git clone https://github.com/devitocodes/devito.git
cd devito
pip3 install -e .
cd ..

sudo apt-get install python3-matplotlib -y
sudo pip3 install jupyter

