#!/bin/bash

echo "#################### Installing build-essential, libelf-dev, libffi-dev"
export DEBIAN_FRONTEND=noninteractive

apt-get update && \
apt-get install -y \
build-essential \
libelf-dev \
libffi-dev \
pkg-config \
wget \
curl \
expect \
python3-pip \
git



echo "#################### Installing Cuda"
wget https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda-repo-ubuntu1804-10-1-local-10.1.105-418.39_1.0-1_amd64.deb
dpkg -i cuda-repo-ubuntu1804-10-1-local-10.1.105-418.39_1.0-1_amd64.deb
apt-key add /var/cuda-repo-10-1-local-10.1.105-418.39/7fa2af80.pub
apt-get update && \
apt-get install -y \
cuda

rm -rf cuda-repo-ubuntu1804-10-1-local-10.1.105-418.39_1.0-1_amd64.deb

export PATH=/usr/local/cuda-10.1/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64:$LD_LIBRARY_PATH



echo "#################### Installing PGI"
#curl 'https://download.pgroup.com/secure/pgilinux-2019-1910-x86-64.tar.gz' \
#  --compressed --output pgilinux-2019-1910-x86-64.tar.gz

tar xpfz pgilinux-2019-1910-x86-64.tar.gz
./run_expect_pgi

rm -rf documentation.html install install_components pgilinux-2019-1910-x86-64.tar.gz

export PGI=/opt/pgi
export PATH=/opt/pgi/linux86-64/19.10/bin:$PATH
export MANPATH=$MANPATH:/opt/pgi/linux86-64/19.10/man
export LM_LICENSE_FILE=$LM_LICENSE_FILE:/opt/pgi/license.dat

export PATH=$PGI/linux86-64/19.10/mpi/openmpi-3.1.3/bin:$PATH
export MANPATH=$MANPATH:$PGI/linux86-64/19.10/mpi/openmpi-3.1.3/man



echo "#################### Installing mpi4py"
env MPICC=/opt/pgi/linux86-64/19.10/mpi/openmpi-3.1.3/bin/mpicc CC=pgcc CFLAGS=-noswitcherror pip3 install --no-cache-dir mpi4py



echo "#################### Installing devito, matplotlib, jupyter notebook"
git clone https://github.com/devitocodes/devito.git
cd devito
pip3 install -e .
cd ..

#apt-get install python3-matplotlib -y
#pip3 install jupyter

